csspath: 
- /settings/css/StyleFile

containerServicesPath: /settings/js/containerSerivceFile.ts
useLocalProxyOnClient: true
localproxy: /settings/localProxy.yaml
pipelineqjson: /settings/qjson/Pipeline.qjson
rootqjson: /static/virement.qjson
fileMap: 
- id: rkjg9140-6ffk-tsb2-g1ta-o2x0mfm7n4ih
  path: /static/depOperations
  name: /errorDialog.qjson
  version: Tue Sep 16 2025 10:11:53 GMT+0300 (GMT+03:00)
- id: mkvhjgpc-32v9-n58x-t3fj-zwc0mfm7qygp
  path: /static/depOperations
  name: /successDialog.qjson
  version: Tue Sep 16 2025 10:11:28 GMT+0300 (GMT+03:00)
- id: 5abtd9e4-duz6-fbww-y38i-02o0mevcnhiq
  path: /static/depOperations
  name: /Dashboard.qjson
  version: Thu Aug 28 2025 14:57:45 GMT+0300 (GMT+03:00)
- id: giqcj333-pen0-gbt9-shcl-pdn0mevcnhi9
  path: /static
  name: /Login.qjson
  version: Thu Aug 28 2025 14:57:45 GMT+0300 (GMT+03:00)
- id: e2magicx-a9dl-9u2n-k2p6-lb70mews3fuq
  path: /static
  name: /withdraw.qjson
  version: Fri Aug 29 2025 14:57:50 GMT+0300 (GMT+03:00)
- id: 440jsvfs-x91u-grx0-38nu-ygv0mf5bn4fq
  path: /static
  name: /virement.qjson
  version: Thu Sep 04 2025 14:27:10 GMT+0300 (GMT+03:00)
- id: wj3j1gqe-fnqn-3j10-vinh-6ll0mf59y65l
  path: /static/depOperations
  name: /virement.qjson
  version: Mon Sep 22 2025 13:31:34 GMT+0300 (GMT+03:00)
- id: 5zrzsjwg-evfg-ble8-4mnk-jh70mfm7n4l7
  path: /static/depOperations
  name: /warningDialog.qjson
  version: Tue Sep 16 2025 10:11:13 GMT+0300 (GMT+03:00)
- id: lhu6xxxm-fl96-7exs-fqr7-woe0mevcnper
  path: /static
  name: /App Settings.appSettings
  version: Tue Sep 16 2025 16:47:25 GMT+0300 (GMT+03:00)
- id: dwwv0vwq-vbpw-z4x0-34v8-5fk0mf0uyznq
  path: /static
  name: /deneme.qjson
  version: Mon Sep 01 2025 11:29:26 GMT+0300 (GMT+03:00)

containerServices: <<containerServices:2kl6ux5m-u980-kj0e-8tcs-7400mewrpfli>>
localProxy: <<localProxy:e5nof9yp-ba4j-u5fi-7vnk-lse0mf6il2g2>>
pipeline: <<pipeline:c4ifnaz9-uagd-js7l-q6x1-ue60mfdy9x33>>

appSettings:
  general:
    containerServices: <<containerServices:2kl6ux5m-u980-kj0e-8tcs-7400mewrpfli>>
    localProxy: <<localProxy:e5nof9yp-ba4j-u5fi-7vnk-lse0mf6il2g2>>
    pipeline: <<pipeline:c4ifnaz9-uagd-js7l-q6x1-ue60mfdy9x33>>
  themeSettings:
    themeModelId: ''
